### PR TITLE
Global component support for editableFields

### PR DESCRIPTION
**Pull request by nathanhebe**
The purpose of this branch is to complete the work to allow stories to have editable config fields that can be assigned to particular story types, then can be edited by a user once added to a canvas.
## Tasks
- [x] A story can define its editable fields
- [x] A canvas admin user can access an edit form for the story
- [x] The editable fields from the story's config will be displayed as form fields
- [x] The user can make edit field values and save or cancel changes
- [x] Only an authorised user can save story edits on a canvas
- [x] A story's field values are serialised and saved into the canvas' JSON
## Secondary Tasks
- [ ] Ability to define available fields types (e.g. text / select list / image or file)
- [ ] Create form components for initial field types
- [x] It would be good to preview 'live' changes on the story as a user edits field values

### CODE REVIEW

**Comment by nathanhebe** [comment]
Initially, you can test the functionality using the rss-generic story.
There is a dev canvas with just that story added [here](http://localhost:4200/canvas/GJ13y9) (local link requires solomon to be running using ember serve)
Try clicking the story handle to flip, then clicking edit. A form should appear from the bottom drawer

FYI. There is a new design for edit forms to appear a slide-out drawer from the right-hand side rather than bottom - but that's not should be an easy swap so no need to worry about that now.

The main issue is to simplify the references to the config fields and ensure consistent bind/observing. E.g when a field's value is edited, the story can easily bind to it and reflect changes.

The canvas also needs to know when fields have been edited to it can re-serialise and save changes

I suggest we merge with the Auth0 branch before we test the saving authentication as there's little point doing it with the old token auth code.

**Comment by nathanhebe** [comment]
Something to note is that it's possible some stories might have an editable field on the back 'flip' of them. So if the editable fields can be aliases to the actual story model (thus can be bound & updated from anywhere the storyModel is available e.g. edit-a-story and story-base) that would be great

**Comment by joshnesbitt** [comment]
Diff of original work [here](https://github.com/hebeworks/Solomon/compare/a9edca046c51cdf1bda946000ae74348a440e2e5...27b289adf0c2479ecff75fae0f007c50468a2905).

**Comment by nathanhebe** [comment]
Basic process at the moment
- Load this [canvas](http://localhost:4200/canvas/GJ13y9)
  - There should be one rss-generic story
  - This story on didReceiveAttrs
    - get's it's storyModel (the story model attached to all stories loaded from a canvas)
    - calls "story.addConfigItem({ name: 'url', type: 'text', value: '', placeholder: 'Enter a URL' });"
      - in story>model this adds the config item if it doesn't already exist
- Click on the dot top right of the blue RSS story
- Click Edit button
  - This triggers an action to open the bottom drawer with the edit-a-story component and passes the story's storyModel as param
- The bottom drawer should open
- There should be one form field
  - this is edit-a-story component that just displays a form field based on `editableFields: Ember.computed.alias('model.config'),`
- Changing the value in the fields _should_ trigger bound events throughout the entire scope that storyModel exists
  - so the change would be available live in the rss-generic story
  - and also available in the parent canvas so the canvas can JSON up the config in order to be saved

**Comment by joshnesbitt** [comment]
Got you @nathanhebe, I'll start investigating.

**Comment by joshnesbitt** [comment]
@nathanhebe this is ready for a review please. I've not managed to reduce the complexity much as I didn't want to refactor too much at once. I think ideally we could have a config manager service which could take care of a lot of this, but for now I'd recommend just using the observer pattern you've used already as to not affect the deadline too much.

I've added the `EditableFields` mixin which you can mix in to any component you wish to support editable config values. These will be persisted automatically on canvas/story save. All you need to do is define an `editableFields: []` array in the component and the mixin should do the rest.

**Comment by joshnesbitt** [comment]
Also, with regards to:

> The user can make edit field values and save or cancel changes

Do we need to add a cancel button on the form?

**Comment by nathanhebe** [comment]
Yes, I think a Save/Cancel (or cancel by closing the bottom drawer)
So we probably need to save the initial field values to revert.
That should be flexible and allow live preview of edits but not persist anything until save

**Comment by joshnesbitt** [comment]
Sure thing, will take a look.

**Comment by joshnesbitt** [comment]
Will look at the secondary tasks too.

**Comment by joshnesbitt** [comment]
I've ticked off:

> It would be good to preview 'live' changes on the story as a user edits field values

The RSS and text component will automatically update. The main problem we've got is the bottom drawer is enabling the blur on the canvas. Not sure what you'd like to do about this? As a work around I've made the drawer close on save/cancel so you can immediately see changes reflected following a config change.

**Comment by nathanhebe** [comment]
Yes it will be really nice to preview the changes. What I was thinking that we’d open the bottomDrawer without the blur when editing - so we can see live changes to the story! (Ultimately, it might be nice to render the story in the bottom drawer next to the form fields?)
If we pass through a flag in the config and make this optional? https://github.com/hebeworks/Solomon/blob/story_config_editing/app/application/controller.js#L153

**Comment by joshnesbitt** [comment]
@nathanhebe yup on it.

**Comment by nathanhebe** [comment]
@joshnesbitt you don't seem to be able to edit a story when it's first added to a canvas.
Here's a screencast to explain but basically after adding, I can't edit until I reload canvas? One of the attempts on the cast didn't show up in the story, but I clicked save and then refreshed and the edit were there?

http://d.pr/i/132IJ/4KXKfUL5

**Comment by joshnesbitt** [comment]
@nathanhebe those issues should be fixed. Mind testing?

**Comment by nathanhebe** [comment]
+1 Tested with new canvas / adding new story & editing straight away - looks good @joshnesbitt

**Comment by joshnesbitt** [comment]
:ship: :shipit: :ship:

**Pull request merged**
