### PR TITLE
Fix unclosed element

### PR DESCRIPTION
**Pull request by pezholio**
Had trouble getting this up and running, and tracked it down to this unclosed `p` element. All working fine in dev now!

### CODE REVIEW

**Comment by roomman** [comment]
Hi @pezholio and thanks very much for contributing. @nathanhebe will pull this soon.

**Comment by pezholio** [comment]
Excellent. Will submit some more PRs if I notice anything else :+1:

**Comment by nathanhebe** [comment]
Hi pezholio, thanks again for your input, we're just doing some house keeping on the repo so I'm going to close this pull request down, but your suggested change was made to the code. Cheers

**Comment by pezholio** [comment]
Cool cool, thanks for letting me know :+1:

**Pull request closed without merging**
