### PR TITLE
PR to test linking to development version of BID Addon

### PR DESCRIPTION
**Pull request by nathanhebe**
Test linking to addon development https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5#link-to-addon-while-developing

### CODE REVIEW

**Comment by nathanhebe** [comment]
## Linking to local dev NPM project

In the addon directory
`npm link`
In the host (Solomon) app directory
`npm link bid-leeds` (where `bid-leeds` is the addon package name
In the host `package.json` add a dependency to the addon e.g. `"bid-leeds":"0.0.0"`
In the host directory `npm install`
`ember serve`

**Comment by nathanhebe** [comment]
Currently working integration with the [BID Addon](https://github.com/hebeworks/solomon-addon-bid-leeds/tree/268e65eab49de74ec4b25646b60ab9a96b2da0dc)

**Comment by nathanhebe** [comment]
## Installing NPM package from git repo
- `npm install git://github.com/organisation/repo.git

**Comment by nathanhebe** [comment]
All story paths in database will need updating to absolute component path to prevent logic in story model https://github.com/hebeworks/Solomon/issues/38

**Comment by SteAllan** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0PUEm29v&#x2F;23-manipulation-panel"> Manipulation Panel</a>

**Pull request merged**
