### PR TITLE
Add delete Canvas functionality

### PR DESCRIPTION
**Pull request by SteAllan**
- [x] Add new UI components
- [x] Add delete endpoint
- [ ] Handle the User deleting the Canvas they navigated to the Gallery from
- [ ] Check to see if there's an issue redirecting to a newly created canvas
  - possibly due to the newly assigned permissions then subsequent isAllowed check?

### CODE REVIEW

**Comment by SteAllan** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wHWP2me0&#x2F;135-delete-a-canvas"> Delete a Canvas</a>

**Comment by SteAllan** [comment]
Button has been added to template along with initial permission checks. Just needs actual delete functionality adding in.

Also need to change the actions as currently the whole component loads the canvas when clicked. This overrides the delete action now that button is in there.

**Comment by nathanhebe** [comment]
@SteAllan this is working basically at the moment. If a user has delete permissions, the delete button will appear - haven't looked at implementing the action yet, but seems to work well with mixed canvas permissions

**Comment by nathanhebe** [comment]
It's not ideal at the moment though as we're making a request each time we want to check the permissions and as its not actually used for security, just ux think we might be better going back to a previous option, where the user's payload from the server contained their object permissions so these check can be done client side. The reason we didn't do that is because the permissions may become outdated, it was duplicating server functionality and also future group permissions wouldn't be included. But since then we've improved integration of user properties with the simple auth session, it's only being used for UI logic, and we could construct user permissions based on group membership on the server before returning the user payload.

**Comment by nathanhebe** [comment]
Implemented delete endpoint in the api now and hooked up all the delete canvas actions.
screen capture on 2016-04-30 at 19-25-16

**Comment by SteAllan** [comment]
Note to self: tweak the layout so all the delete buttons are aligned with each other. Looks messy with them all at different vertical positions.

**Comment by SteAllan** [comment]
'Delete' buttons are now aligned.

**Comment by SteAllan** [comment]
Need to add an 'are you sure?' prompt when the user clicks the 'delete' button.

**Comment by SteAllan** [comment]
Confirmation prompt is in.

Have an issue if you delete the Canvas you navigated to the Gallery from: if you then press the Back button, it loads the Canvas in, until the next refresh, when it can't be found.

**Comment by SteAllan** [comment]
Canvas item heights are now rematched after a Canvas is deleted.

**Pull request merged**
