### PR TITLE
User Authentication Fixes

### PR DESCRIPTION
**Pull request by nathanhebe**
### About

Feedback from testing Auth0 Functionality on Solomon
### Known Issues
- [x] The first time I try to access one of my own canvases, it says it can't find it. It's only on the first visit to the canvas, though: subsequent visits are fine.
- [x] Newly created canvas doesn't appear to load correctly, causing the same canvas to be shown

### CODE REVIEW

**Comment by nathanhebe** [comment]
Once logged in I am unable to add a story to my canvas. My canvas is correctly listed on the gallery page, I can navigate to it, but I get the unauthorised "do you want to duplicate this canvas message"

**Comment by SteAllan** [comment]
After creating my own canvas I was able to add a single story to it but then encountered the same issue and couldn’t add anymore.

**Comment by barrettmark** [comment]
On this screen, would it be possible to add a register button under the login as the signup button on the next screen felt a bit hidden for me
screen shot 2016-02-09 at 11 54 58

**Comment by joeldavidmercer** [comment]
I'm Encountering the same 'Duplicate Canvas' Issue. Also to expand upon that, when I Log in create a canvas, then Log out and log back in again without leaving the canvas it no longer recognises it as belonging to me and I get the 'Duplicate Canvas' modal again.

**Comment by roomman** [comment]
+1 on the single Story only issue flagged by @SteAllan. Regarding @barrettmark's suggestion, can we skip that first modal and jump right to the Auth0 login screen?

**Comment by nathanhebe** [comment]
@barrettmark Would "Login/Register" text on the button suffice, or do you want changes to the "sign up" button on the Auth0 side?

screen shot 2016-02-09 at 12 02 42

**Comment by barrettmark** [comment]
Sounds good @roomman - I think that'd help

**Comment by joshnesbitt** [comment]
@roomman @barrettmark will get the Auth0 screen showing straight away. @SteAllan @joeldavidmercer @nathanhebe looking into that bug.

**Comment by joshnesbitt** [comment]
@nathanhebe @SteAllan @joeldavidmercer @roomman @barrettmark pushed some fixes. Mind checking again?

**Comment by nathanhebe** [comment]
@SteAllan @barrettmark @joeldavidmercer @roomman @joshnesbitt 
This latest has been deployed to preview. Please could you all take a min to check over the Auth fixes mentioned above and report any issues or +1 if everything Auth-related looks good.
http://preview.mysolomon.co.uk
Cheers

**Comment by joshnesbitt** [comment]
Thanks @nathanhebe will take a look.

**Comment by roomman** [comment]
Two issues that I could spot: 
- displaying a "couldn't find" error when returning to a new Canvas for the first time
- adding the selection of Stories added to my previous Canvas when adding a new Canavs

**Comment by nathanhebe** [comment]
@roomman 
I can't replicate the "couldn't find" issue although I have seen that before.
Please can you explain the second issue a bit more? Is it adding extra stories to a new canvas?

**Comment by SteAllan** [comment]
Logging in is all fine for me. But, the first time I try to access one of my own canvases, it says it can't find it. It's only on the first visit to the canvas, though: subsequent visits are fine.

**Comment by joshnesbitt** [comment]
@SteAllan @roomman on those bugs now.

**Comment by nathanhebe** [comment]
@joshnesbitt the first issue with the "couldn't find" could be an issue with the length of time to initially load a newly created canvas. At the moment the error message is prompted by canvas-element in didRenderElement - checking to see if its canvas model exists. This might be too early for the canvas route model's promise to be fulfilled - might just need to move
`this.set('appSettings.errorMessage',"Sorry we can't find the canvas you were looking for. Try find one using the Gallery link");`
to canvas route's model method if `params.canvas_id` is empty - fire the error message from there?

**Comment by joshnesbitt** [comment]
@nathanhebe yup that's a great shout.

**Comment by joshnesbitt** [comment]
@nathanhebe I think [this](b.com/hebeworks/Solomon/commit/e45c35a1c546d03c6e7a4255e502a85fbcb7e043) should fix the 404 modal issue. Sorry about the noisy diffs, cleaning up each file as I go with some sublime plugins for formatting etc!

**Comment by joshnesbitt** [comment]
@nathanhebe I believe I've fixed both those issues now. The second one that @roomman reported was a right bugger. I think this may have resulted in odd behaviour in the past too.

As the [component was using an array shared across all instances](https://github.com/hebeworks/Solomon/commit/cacda577fc432d1e9386f69f640a41a154c53f8c#diff-925d9180af3b51b407c2b3555e6c30c4L11), newly created canvases could always reference the stories and categories from the previous canvas. I've moved this to be a computed property that [resets when a new model is loaded in](https://github.com/hebeworks/Solomon/commit/cacda577fc432d1e9386f69f640a41a154c53f8c#diff-925d9180af3b51b407c2b3555e6c30c4R22).

**Comment by nathanhebe** [comment]
Josh has sorted those two issues now - http://preview.mysolomon.co.uk
Please can y'all check & report back issues or +1 - TA
@SteAllan @barrettmark @joeldavidmercer @roomman @joshnesbitt

**Comment by SteAllan** [comment]
Still getting the issue with not finding the canvas on first visit.

**Comment by joshnesbitt** [comment]
@SteAllan arg! Will keep looking.

**Comment by nathanhebe** [comment]
Deployed to http://preview.mysolomon.co.uk

**Comment by SteAllan** [comment]
+1

**Comment by joeldavidmercer** [comment]
+1 means good right? I'm not encountering any problems works great for me.

**Comment by joshnesbitt** [comment]
@joeldavidmercer ha yes!

**Comment by roomman** [comment]
+1

**Comment by roomman** [comment]
Awesome work!

**Pull request merged**
