### PR TITLE
Starting PR Add Markdown as editable field type

### PR DESCRIPTION
**Pull request by nathanhebe**
# Add Markdown as an editable field type
- [ ] Add editable field type to component editable fields mixin
- [ ] Add suitable editing form to edit a story component
- [ ] Allow markdown to be rendered correctly as a bound property in a component
- [ ] Have a way of previewing the result of markdown content in an editable field

### CODE REVIEW

**Comment by nathanhebe** [comment]
# Demo of editing markdown fields with live preview

screen capture on 2016-02-13 at 16-23-36

**Comment by nathanhebe** [comment]
@SteAllan Please could you do me a favour and suggest how we can apply specific styles to markdown content using standard elements? At the moment it seems to require too much specific markup in the content for user input 

For example
- [To get the blue colour on the bold requires adding an attribute to the span class](https://github.com/hebeworks/Solomon/blob/nhs_rtt_dashboard/app/components/stories/complete/nhs-rtt/value-title-with-text/template.hbs#L4)
  - there's no way a user could enter this and we want to control it for consistency 
  - it would be great if we could cascade this from the parent element and use generic/semantic elements
    - e.g. the markdown converter changes emphasis `**` to `<strong>`
      - so is there a way that fits in with the style methodology to make `<strong>` elements within `spc-vtwt_title` extend `cpn-color="blue"` [here](https://github.com/hebeworks/Solomon/blob/nhs_rtt_dashboard/app/styles/components/stories/_nhs-rtt/value-title-with-text.scss)

**Comment by SteAllan** [comment]
@nathanhebe I'm happy that `<strong>` fits in with our style methodology. I'd say that the bold text being blue is a story-level override: we wouldn't want bold text being blue across the app. So I think it's most appropriate that this story simply makes bold text like this blue through CSS.

**Comment by nathanhebe** [comment]
Cheers. I just added the blue colour to strong in the [story-specific stylesheet](https://github.com/hebeworks/Solomon/blob/nhs_rtt_dashboard/app/styles/components/stories/_nhs-rtt/value-title-with-text.scss#L16)

**Pull request merged**
